stop();
pizza.text = _root.LocaleText.getText("pizza_hotcheese");
topping1.text = _root.LocaleText.getText("topping_cheese");
topping2.text = _root.LocaleText.getText("topping_hotsauce");
_parent.normalsauceREQUESTED = false;
_parent.hotsauceREQUESTED = true;
_parent.cheeseREQUESTED = true;
_parent.topping1REQUESTED = false;
_parent.topping2REQUESTED = false;
_parent.topping3REQUESTED = false;
_parent.topping4REQUESTED = false;
_global.pizzatron_dl.setPizzaType = "NO TOPPINGS";
