stop();
pizza.text = _root.LocaleText.getText("pizza_spicyseaweed");
topping1.text = _root.LocaleText.getText("topping_cheese");
topping2.text = _root.LocaleText.getText("topping_hotsauce");
topping3.text = "5 " + _root.LocaleText.getText("topping_seaweeds");
_parent.normalsauceREQUESTED = false;
_parent.hotsauceREQUESTED = true;
_parent.cheeseREQUESTED = true;
_parent.topping1REQUESTED = true;
_parent.Ntopping1REQUESTED = 5;
_parent.topping2REQUESTED = false;
_parent.topping3REQUESTED = false;
_parent.topping4REQUESTED = false;
_global.pizzatron_dl.setPizzaType = "5 TOPPINGS";
