stop();
pizza.text = _root.LocaleText.getText("pizza_hotfishshrimp");
topping1.text = _root.LocaleText.getText("topping_cheese");
topping2.text = _root.LocaleText.getText("topping_hotsauce");
topping3.text = "2 " + _root.LocaleText.getText("topping_shrimps");
topping4.text = "2 " + _root.LocaleText.getText("topping_fishies");
_parent.normalsauceREQUESTED = false;
_parent.hotsauceREQUESTED = true;
_parent.cheeseREQUESTED = true;
_parent.topping1REQUESTED = false;
_parent.topping2REQUESTED = true;
_parent.Ntopping2REQUESTED = 2;
_parent.topping3REQUESTED = false;
_parent.topping4REQUESTED = true;
_parent.Ntopping4REQUESTED = 2;
_global.pizzatron_dl.setPizzaType = "2x2 TOPPINGS";
