stop();
pizza.text = _root.LocaleText.getText("pizza_liquoricemarshmallow");
topping1.text = _root.LocaleText.getText("topping_sprinkles");
topping2.text = _root.LocaleText.getText("topping_chocolatesauce");
topping3.text = "2 " + _root.LocaleText.getText("topping_liquorices");
topping4.text = "2 " + _root.LocaleText.getText("topping_marshmallows");
_parent.normalsauceREQUESTED = true;
_parent.hotsauceREQUESTED = false;
_parent.cheeseREQUESTED = true;
_parent.topping1REQUESTED = true;
_parent.Ntopping1REQUESTED = 2;
_parent.topping2REQUESTED = false;
_parent.topping3REQUESTED = true;
_parent.Ntopping3REQUESTED = 2;
_parent.topping4REQUESTED = false;
_global.pizzatron_dl.setPizzaType = "2x2 TOPPINGS";
