stop();
pizza.text = _root.LocaleText.getText("pizza_fishdish");
topping1.text = _root.LocaleText.getText("topping_cheese");
topping2.text = _root.LocaleText.getText("topping_pizzasauce");
topping3.text = "2 " + _root.LocaleText.getText("topping_squids");
topping4.text = "2 " + _root.LocaleText.getText("topping_fishies");
_parent.normalsauceREQUESTED = true;
_parent.hotsauceREQUESTED = false;
_parent.cheeseREQUESTED = true;
_parent.topping1REQUESTED = false;
_parent.topping2REQUESTED = false;
_parent.topping3REQUESTED = true;
_parent.Ntopping3REQUESTED = 2;
_parent.topping4REQUESTED = true;
_parent.Ntopping4REQUESTED = 2;
_global.pizzatron_dl.setPizzaType = "2x2 TOPPINGS";
